// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "^;;fpq$Wsr%F98l_x1:!":
            case "carl":return img`
. . . . . . 5 5 5 5 . . . . . . 
. . . . 5 5 5 5 5 5 5 . . . . . 
. . . . 5 5 4 4 4 5 5 5 . . . . 
. . . . . 4 6 4 4 6 4 5 . . . . 
. . . . . 4 4 4 4 4 4 . . . . . 
. . . . . 4 2 4 4 2 4 . . . . . 
. . . . . 4 2 2 2 2 4 . . . . . 
. . . . . 4 4 4 4 4 4 . . . . . 
. . . . 8 8 4 4 4 4 8 8 . . . . 
. 4 4 6 8 8 6 6 8 8 8 8 8 4 4 . 
. 4 4 6 6 8 8 8 8 8 8 8 8 4 4 . 
. . . . 6 6 8 8 8 8 8 8 . . . . 
. . . . . 6 8 . . 6 8 . . . . . 
. . . . . 6 6 . . 6 8 . . . . . 
. . . . . 6 6 . . 6 8 . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image1":
            case "karl":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
